openapi: 3.0.0
info:
  title: Calculator API
  description: API for performing basic arithmetic calculations
  version: 1.0.0
servers:
  - url: http://localhost:8000
  - url: http://localhost:3000

paths:
  /api/v1/calculator/sum:
    post:
      summary: Calculate sum of two numbers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                num1:
                  type: number
                  example: 5
                num2:
                  type: number
                  example: 5
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      sum:
                        type: string
                        example: "10.00"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: fail
                  message:
                    type: string
                    example: fields num1,num2 are required and must be numbers
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: something went wrong!
